CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    email  VARCHAR(255) NOT NULL UNIQUE,
    name        VARCHAR(255),
    api_key     VARCHAR(255) NOT NULL UNIQUE,
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)